# Generated by Django 5.2.4 on 2025-07-26 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercicio', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('dia_da_semana', models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('exercicios', models.ManyToManyField(related_name='treinos', to='exercicio.exercicio')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos', to='personal.personal')),
            ],
        ),
    ]
