# Generated by Django 5.2.4 on 2025-07-27 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
        ('treino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treino',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treinos', to='aluno.aluno'),
        ),
    ]
