# Generated by Django 5.2.4 on 2025-07-26 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_exercicio', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='exercicios/imagens/')),
                ('video', models.FileField(blank=True, null=True, upload_to='exercicios/videos/')),
                ('grupo_muscular', models.CharField(choices=[('peito', 'Peito'), ('costas', 'Costas'), ('ombros', 'Ombros'), ('biceps', 'Bíceps'), ('triceps', 'Tríceps'), ('abdomen', 'Abdômen'), ('gluteos', 'Glúteos'), ('quadriceps', 'Quadríceps'), ('posterior_coxa', 'Posterior da Coxa'), ('panturrilha', 'Panturrilha'), ('antebraco', 'Antebraço')], default='peito', max_length=20)),
                ('series', models.PositiveSmallIntegerField(choices=[(1, '1 série'), (2, '2 séries'), (3, '3 séries'), (4, '4 séries'), (5, '5 séries')], default=3)),
                ('repeticoes', models.PositiveSmallIntegerField(choices=[(6, '6 reps'), (8, '8 reps'), (10, '10 reps'), (12, '12 reps'), (15, '15 reps')], default=10)),
                ('carga', models.CharField(choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('padrao', 'Padrão'), ('maxima', 'Máxima')], default='padrao', max_length=10)),
                ('descanso', models.PositiveSmallIntegerField(choices=[(30, '30 segundos'), (45, '45 segundos'), (60, '1 minuto'), (90, '1 minuto e 30'), (120, '2 minutos'), (180, '3 minutos ou mais')], default=60)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='personal.personal')),
            ],
        ),
    ]
