# Generated by Django 5.2.4 on 2025-07-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media/exercicios/imagens/'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/exercicios/videos/'),
        ),
    ]
